### ISSUE TITLE
HDP 2.3 Repo URL

### ISSUE THREAD

**Issue by nallagangus** [sequenceiq/docker-ambari#70] opened 2015-07-29 14:33 UTC
I installed sequence/ambari docker successfully and started Ambari UI.

But following repo's seems to be unreachable ? Can some one help with correct URL's

HDP 2.3 
http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.3.0.0

HDP-UTILS-1.1.0.20
http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6

**Comment by keyki** [comment] 2015-07-29 14:35
Which version of Ambari docker did you use? I think the issue is that you cannot resolve anything not just those repost.

If you use the sequenceiq/ambari:2.1.0-consul and use the ambari functions on that branch it will work.

**Comment by nallagangus** [comment] 2015-07-29 14:36
I pulled latest I think - which is sequence/ambari

**Comment by nallagangus** [comment] 2015-07-29 14:54
I ran 2.1.0-consul and I had the same problem. I doubt if these public repos are unavailable

**Comment by keyki** [comment] 2015-07-29 15:02
How do you run the containers? Can you copy the command here please?

**Comment by nallagangus** [comment] 2015-07-29 15:05
docker run -d -p 8080 --name ambari-node0 sequenceiq/ambari:2.1.0-consul

I was able to start the Ambari UI w/o issues. Then when I am trying to create the cluster it ave me options to choose HDP2.3 HDP2.2 etc and when I slected one of those It is failing to proceeding to next step with errors pointing to 400 Error code while accessing public repo's

Thanks for the help ..

**Comment by keyki** [comment] 2015-07-29 15:43
These containers rely on an external service to resolve hostnames. Could you please download this ambari-functions script https://github.com/sequenceiq/docker-ambari/blob/2.1.0-consul/ambari-functions source it and use `amb-start-cluster 3` and it will launch 1 consul container for the DNS 1 ambari-server and 2 agent nodes. From this point you can use the Ambari and it will work fine.

**Comment by nallagangus** [comment] 2015-07-29 16:27
Thanks.

Does Consul provide "DNS services"?  How do I start a consul server and add hosts and identify external repos to same?

**Comment by keyki** [comment] 2015-07-29 18:00
We register manually the ambari-agents as services, (you can check the functions script for this) so within the cluster every container will be able to resolve the ambX.service.consul names and consul as a fallback option is configured to use the 8.8.8.8 for resolving external hostnames. 

https://github.com/sequenceiq/docker-ambari/blob/2.1.0-consul/ambari-functions#L119

**Closed** 2015-07-29 18:16 UTC

**Comment by nallagangus** [comment] 2015-07-30 02:59
I am getting these errors: url: (7) Failed to connect to 172.17.0.1 port 8500: Operation timed out
when I used mentioned scripts to start amb-start-cluster 3

**Comment by keyki** [comment] 2015-07-30 05:38
Add the appropriate routing, like: `sudo route add -net 172.17.0.0/16 192.168.59.103`

**Comment by nallagangus** [comment] 2015-07-30 14:49
Thank you..that did the trick and got one step closer..

Ambari-Web UI is asking for ssh-authorized keys to register other hosts. how do we gracefully handle this(Python programmer would say - pythonise this..:)) . Do we need to run docker kick off sshd on each of servers (amb-server to amb1 , amb2) and then create keys and distribute private key of ambari-server to others in cluster? 

sudhir

**Comment by nallagangus** [comment] 2015-07-30 16:05
I skipped "ssh keys" as ambari-agents are running on all hosts but next step of "host checks failed" with errors saying 1) firewall running on all nodes and 2) ntpd deamon is not running. doesn't ambari-functions  code cover these 2 aspects?

**Comment by keyki** [comment] 2015-07-30 16:10
We strictly rely on blueprints where these issues don't come up, other than that business as usual as you would do on any hosts.
